repos:
    -   repo: https://github.com/psf/black
        rev: stable
        hooks:
        - id: black
          python-version: python3.8
          files: ^((src)\/.+|config|tests|clients)\.py$
          verbose: true
